# fly.toml app configuration file generated for offmarketsource on 2026-05-12T21:29:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'offmarketsource'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  LANDFINDER_AUTH_USER = 'team'
  PORT = '3000'

[[mounts]]
  source = 'landfinder_data'
  destination = '/app/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
